%%
% This script calls the mnh_zmap_predict for harmonizing incoming cross-spectrum which requires the supplied norm file.


clear;

%%
% file of norm: used for harmonizing cross spectrum 
% please download from Synapse https://doi.org/10.7303/syn26712979, 
% it was calculated with data https://doi.org/10.7303/syn26712693, the training will released soon
path_norm='D:\EEG\HarMNqEEG\data\example\norm\norm_riemlogm_gfavfa_bava_study.mat';

% data table of incoming data: the data to be harmonized
% the table can be generated by step1
path_Dps='.\result\DPs_riemlogm_1201_TDBrain.csv';
% path of folder to save the result
path_out='.\result\';



% load neccesary variables for the prediction, which defined in training progress
%   tregs: saved regression model for training data table
%   level: levels definition of the hamonization model
%   batch: batch definition, which has to match the norm file load above,
%          which fixed to {'study'} as the result of model compare in the paper
%   resp: responses to be regressed
%   opt: options of the harmonization and regression parameter
mnhs=load(path_norm,'tregs','level','batch','resp','opt');
% set parameter in the structure for mnh_zmap_predict
mnhs.path_table=path_Dps;
mnhs.path_out=path_out;
%batchs = {'study'};

% define which exsit batch to be used as the reference batch of incoming data
%  use as {'incomingBatchName', 'existBatchNameInNorm';'incomingBatchName', 'existBatchNameInNorm';...}
mnhs.reRefBatch={'The Netherlands_Deymed','Medicid-3M Cuba1990'};
% The tag to be append to the filename of output table to distinguish the project you are running with others. 
% Replace with your own task name
mnhs.tag=['zscore'];
% load data with the information above 
%mnhs.ref='Medicid-3M Cuba1990';
mnhs=mnh_create_predict(mnhs);



%% the table with harmonized data and its zscore will be saved in the caller
mnhs=MnhCaller(mnhs);


